# docker-compose.yml
version: "3.8"

services:
    admin-ui:
        build:
            context: ./frontend/admin-ui
        container_name: admin-ui
        ports:
            - "3000:80"
        networks:
            - ui_app_network
