# docker-compose.yml
version: "3.8"

services:
    backend:
        build:
            context: ./backend
        container_name: backend
        expose:
            - "8000"
        networks:
            - app_network
        volumes:
            - ./backend/src:/app/src

networks:
    app_network:
        driver: bridge
